apiVersion: apps/v1
kind: Deployment
metadata:
  name: angular
  namespace: arun
  labels:
    app: arun
spec:
  replicas: 2
  selector:
    matchLabels:
      app: arun
  template:
    metadata:
      labels:
        app: arun
    spec:
      containers:
        - name: angular
          image: redbull.azurecr.io/augular:1.0.0
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 80
      imagePullSecrets:
        - name: arunbachi
